version: '3.3'
services:
    traefik:
        hostname: docker_emperor_traefik
        image: traefik:latest
        container_name: docker_emperor_traefik
        restart: always
        networks:
            - docker_emperor_traefik_proxy
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        # environment:
        #     - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
        #     - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
        # labels:
        #     - "traefik.enable=true"
        #     - "traefik.backend=traefik"
        #     - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"  
        #     # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /traefik"
        #     - "traefik.port=8080"
        #     - "traefik.docker.network=docker_emperor_traefik_proxy"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            # - ${USERDIR}/docker/traefik:/etc/traefik
            # - ${USERDIR}/docker/shared:/shared

# docker network create docker_emperor_traefik_proxy
networks:
    docker_emperor_traefik_proxy:
        external:
            name: docker_emperor_traefik_proxy
